import { Metadata } from 'next'
import * as React from 'react'

export const metadata: Metadata = {
    title: 'Games',
    description: 'Generated by create next app',
}

function GamesLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>
}

export default GamesLayout
