export const phrases = [
  { phrase: "Go akga loleme", meaning: "To lie" },
  { phrase: "Go anetswa dipodi", meaning: "To be gotten the better of" },
  {
    phrase: "Go apeela thukgwi/noko le mala",
    meaning: "To leave nothing behind",
  },
  {
    phrase: "Go bapalela ditloo mo kgetsing e e letshoba",
    meaning: "To work hard without gaining anything",
  },
  {
    phrase: "Go bapalela mo kgetsing e e letshoba",
    meaning: "To save one's earnings in a bottomless purse",
  },
  {
    phrase: "Go bapolela dimapo tlapeng",
    meaning: "To waste time on something that won't yield",
  },
  {
    phrase: "Go batla gotswana lwa phiri",
    meaning: "To seek a needle in a haystack",
  },
  { phrase: "Go baya pelo", meaning: "Be patient or to cool down" },
  {
    phrase: "Go beeletsa motlhatswa ka tshega",
    meaning: "To show ownership with property",
  },
  { phrase: "Go bega pitsa o tshotse molelo", meaning: "To take a big risk" },
  {
    phrase: "Go betsana ka noga e utlwa",
    meaning: "To be in conflict with one another",
  },
  { phrase: "Go bipa mpa ka mabele", meaning: "To hide a secret" },
  {
    phrase: "Go bogola poo e tsweletse ka go bopa",
    meaning: "To keep retrying unsuccessfully",
  },
  { phrase: "Go bokalatsa dintshi", meaning: "To sleep with eyes half closed" },
  { phrase: "Go bona ka letshotsha", meaning: "To find something by accident" },
  { phrase: "Go bona nta di fuduga", meaning: "To get in big trouble" },
  {
    phrase: "Go bonela letsatsi pele",
    meaning: "To be born or more experienced first",
  },
  { phrase: "Go botsa katloko", meaning: "To cross question someone" },
  {
    phrase: "Go bowa ka nngoba e sa fotlhwa",
    meaning: "To return empty handed",
  },
  { phrase: "Go bua diphirimisi", meaning: "To talk nonsense" },
  { phrase: "Go bua ga se go dira", meaning: "To speak is not to act" },
  { phrase: "Go bua gabedi o se mo gama leshole", meaning: "To be two-faced" },
  { phrase: "Go di emela", meaning: "To face the music" },
  {
    phrase: "Go di ga o di tlatsa kobo di sena morwadi",
    meaning: "Don't run away with more than you can carry.",
  },
  { phrase: "Go di gama o sa di tlhapela", meaning: "To be in trouble" },
  { phrase: "Go di gama o sa di tlhapela", meaning: "To get in trouble" },
  { phrase: "Go di gamela mo thotaneng", meaning: "To have problems" },
  { phrase: "Go di kapa", meaning: "To be drunk" },
  {
    phrase: "Go di tlhaolela di bekerwe",
    meaning:
      "Locking the stable door when the steed is stolen. To react too late",
  },
  { phrase: "Go direlwa fela o se naga", meaning: "To have things easy" },
  {
    phrase: "Go e nametsa thaba e tlhotsa",
    meaning: "To increase someone's problems",
  },
  { phrase: "Go ema motho nokeng", meaning: "To support or help someone" },
  { phrase: "Go epela selepe", meaning: "To make peace" },
  { phrase: "Go epela selepe", meaning: "To bury the hatchet" },
  { phrase: "Go eta ka loleme", meaning: "To enjoy a foreign language" },
  {
    phrase: "Go fa wa bo o ipeela",
    meaning: "To give away is to put away for yourself",
  },
  { phrase: "Go fatlha magotlo", meaning: "To pee" },
  {
    phrase: "Go fetanwa go dirwa mmogo",
    meaning: "Competition is the soul of business",
  },
  {
    phrase: "Go fetoga ga se molato",
    meaning: "To change one's mind is not a crime",
  },
  { phrase: "Go fetoga phuti boloko", meaning: "To run away" },
  {
    phrase: "Go fisa baeng marago",
    meaning: "To speed the parting of the guest",
  },
  { phrase: "Go fitlha lesiela", meaning: "To hide discomforts" },
  {
    phrase: "Go fitlhela bana ba tladi ba ntse dibothwana-bothwana",
    meaning: "To get in big trouble",
  },
  { phrase: "Go fitlhela naga e le tshetlha", meaning: "To find nobody" },
  { phrase: "Go goga motho loleme ese kgaga", meaning: "Silence is golden" },
  {
    phrase: "Go gogola dikgomo ka mono-wa-thoko",
    meaning: "To get rich with no effort",
  },
  {
    phrase: "Go gopolwa ka kgamelo",
    meaning: "To remember a person when you need something from them",
  },
  { phrase: "Go hura-hura dipabi ka meno", meaning: "To shiver with cold" },
  { phrase: "Go ikodisa dibi", meaning: "To fling one's handkerchief" },
  {
    phrase: "Go ikoketsa marago ka majwe",
    meaning: "To act like you are better than others",
  },
  { phrase: "Go ikutlwisa mathaithai", meaning: "To play dirty tricks" },
  {
    phrase: "Go inaya naga",
    meaning: "To flee or run away",
  },
  { phrase: "Go inosa ka nkgo", meaning: "Have first experience of something" },
  { phrase: "Go ipha naga", meaning: "To  flee or run away" },
  {
    phrase: "Go ipolaya wa tloga wa re o loilwe",
    meaning: "To blame bad luck for the consequences of your own actions.",
  },
  {
    phrase: "Go irela gau sa lonaka",
    meaning: "To avoid using something damaged or unsuitable for its purpose.",
  },
  { phrase: "Go isa marapo go beng", meaning: "To go to sleep" },
  { phrase: "Go isa nonyane Borwa", meaning: "To do an unnecessary task" },
  {
    phrase: "Go isa phuduhudu bosarwa",
    meaning: "To repeat something that has already been completed",
  },
  { phrase: "Go itaana ka noga e tshela", meaning: "To hate each other" },
  { phrase: "Go itaya ka kwano", meaning: "To miss the target" },
  { phrase: "Go itaya kgomo lonaka", meaning: "To be correct and on point" },
  { phrase: "Go itaya se folletse", meaning: "To fail" },
  { phrase: "Go itekanya morwalo", meaning: "To make the garden" },
  {
    phrase: "Go itewa ke sechane",
    meaning: "To be struck with disappointment",
  },
  { phrase: "Go itlantla diteme", meaning: "To lack truth" },
  { phrase: "Go itlhaba ngololo", meaning: "To sham indifference" },
  {
    phrase: "Go itlhatlaganyetsa magala tlhogong",
    meaning: "To exaggerate one's circumstances",
  },
  { phrase: "Go itoma sekgono", meaning: "To swear on the impossibility" },
  {
    phrase: "Go itsala jaaka peba",
    meaning: "To inherits one's traits either good or bad",
  },
  {
    phrase: "Go itshela moriti o tsididi",
    meaning: "To act like you don't know",
  },
  { phrase: "Go itshwara madi", meaning: "To kill your relative" },
  { phrase: "Go ja dijo tsa ditoro", meaning: "To have wishful thinking" },
  {
    phrase: "Go ja ga go die, go dia go dira",
    meaning: "To eat does not delay, to work does",
  },
  {
    phrase: "Go ja masepa a bankane ba gago",
    meaning: "To be an underachiever",
  },
  { phrase: "Go ja mokaragana wa botshelo", meaning: "To enjoy life" },
  { phrase: "Go ja monate", meaning: "To enjoy" },
  { phrase: "Go ja motho direthe", meaning: "To spy or gossip about someone" },
  { phrase: "Go jelwa maitlho a tshwene", meaning: "To play dirty tricks" },
  { phrase: "Go jesa dijo tsa ditoro", meaning: "To daydream" },
  { phrase: "Go kalakatlega jaka poo ya mariga", meaning: "To wander about" },
  {
    phrase: "Go kgadisa motswetsana",
    meaning: "To ruin a steady source of wealth or benefit",
  },
  { phrase: "Go kgora ka mpa tsoo pedi", meaning: "To eat too much" },
  { phrase: "Go kgotla semane", meaning: "To be happy and satisfied" },
];
